name: Demo Globoticket Frontend
env:
  HomePage: ''
on:
  push:
    branches:
      - demo
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build with dotnet
        run: dotnet build frontend/frontend.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish frontend/frontend.csproj -c Release -o ${{env.DOTNET_ROOT}}/frontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.6.0
        with:
          name: frontend
          path: ${{env.DOTNET_ROOT}}/frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'globoticket'
          slot-name: 'demo'
          package: .
          
      - name: Set homepage location for next job
        id: set_var
        run: |
          echo "homepage=${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_OUTPUT
