name: Globoticket-ordering

on:
  push:
    branches:
      - main
    paths:
      - 'ordering/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 8.0.x

      - name: Build with dotnet
        run: dotnet build ordering/ordering.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ordering/ordering.csproj -c Release -o ${{env.DOTNET_ROOT}}/ordering

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ordering
          path: ${{env.DOTNET_ROOT}}/ordering

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ordering

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: 'globoticket-ordering'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GLOBOTICKET_ORDERING_PUB_PROFILE }}
          package: .
