name: 03- Deploy New Release Catalog 

on:
  release: 
     types: [published] 
  workflow_dispatch:
     

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: get release artifacts for deployment
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          regex: true
          file: ".*"
          target: './'


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'globoticket-catalog'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GLOBOTICKET_CATALOG_PUB_PROFILE }}
          package: catalog.zip
