name: Globoticket-catalog

on:
  push:
    branches:
      - main
    paths:
      - 'catalog/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build with dotnet
        run: dotnet build catalog/catalog.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish catalog/catalog.csproj -c Release -o ${{env.DOTNET_ROOT}}/catalog

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: catalog
          path: ${{env.DOTNET_ROOT}}/catalog

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: catalog

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'globoticket-catalog'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98EE9D9F97D347CBB9B37A5E50839625 }}
          package: .
