name: 03- Deploy New Release Ordering 

on:
  release: 
     types: [published] 
  workflow_dispatch:
     
jobs:
# We start with deploying the application to Azure Web App. 
# We pull the zip file artifact that contains the web application from the
# release and use it directly to deploy to the web app. After deployment, we 
# generate output, which is the URL we can use to validate the deployment. 
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    outputs:
      homepage: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: get release artifacts for deployment
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          regex: true
          file: ".*"
          target: './'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: 'globoticket-ordering'
          slot-name: 'Production'
          publish-profile: ${{ secrets.GLOBOTICKET_ORDERING_PUB_PROFILE }}
          package: .
